export const API_ERRORS = {
    USER: {
      NOT_FOUND: 'USER_NOT_FOUND',
      ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
      INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
      VALIDATION_ERROR: 'USER_VALIDATION_ERROR'
    },
    CAMPAIGN: {
      NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
      ALREADY_EXISTS: 'CAMPAIGN_ALREADY_EXISTS',
      VALIDATION_ERROR: 'CAMPAIGN_VALIDATION_ERROR',
      SUBDOMAIN_EXISTS: 'CAMPAIGN_SUBDOMAIN_EXISTS',
      INVALID_STATUS: 'CAMPAIGN_INVALID_STATUS',
      DELETE_ERROR: 'CAMPAIGN_DELETE_ERROR',
      CLOUDFLARE_ERROR: 'CAMPAIGN_CLOUDFLARE_ERROR'
    },
    AUTH: {
      UNAUTHORIZED: 'UNAUTHORIZED',
      FORBIDDEN: 'FORBIDDEN'
    },
    SYSTEM: {
      INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
      BAD_REQUEST: 'BAD_REQUEST'
    },
    VALIDATION: {
      INVALID_INPUT: 'INVALID_INPUT'
    },
    NOT_FOUND: 'NOT_FOUND',
    UNAUTHORIZED: 'UNAUTHORIZED',
    MEMBER: {
      NOT_FOUND: 'MEMBER_NOT_FOUND',
      ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
      INVALID_CREDENTIALS: 'MEMBER_INVALID_CREDENTIALS',
      VALIDATION_ERROR: 'MEMBER_VALIDATION_ERROR'
    }

  } as const